[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "embedded", "no-std"]
description = "Runs embedded programs just like native ones"
edition = "2021"
keywords = ["knurling", "cargo-runner"]
license = "MIT OR Apache-2.0"
name = "probe-run"
readme = "README.md"
repository = "https://github.com/knurling-rs/probe-run"
version = "0.3.3"

[dependencies]
addr2line = { version = "0.17", default-features = false, features = [
    "fallible-iterator",
    "std-object",
    "rustc-demangle",
    "cpp_demangle",
] }
anyhow = "1"
colored = "2"
defmt-decoder = { version = "=0.3.2", features = ["unstable"] }
gimli = { version = "0.26", default-features = false }
git-version = "0.3"
log = "0.4.16"
object = { version = "0.27", default-features = false }
probe-rs = "0.13"
probe-rs-rtt = "0.13"
signal-hook = "0.3"
structopt = "0.3"
gdb-server = "0.12.0"

[dev-dependencies]
dirs = "4"
insta = "1.8"
os_pipe = "1.0"
pretty_assertions = "1"
rstest = "0.11"
nix = "0.23"
serial_test = "0.5"
